// Copyright (c) 2025 Alibaba Group Holding Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: api/weather/weather.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherMessageRequest) Reset() {
	*x = GetWeatherMessageRequest{}
	mi := &file_api_weather_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherMessageRequest) ProtoMessage() {}

func (x *GetWeatherMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherMessageRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherMessageRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetWeatherMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherMessageResponse) Reset() {
	*x = GetWeatherMessageResponse{}
	mi := &file_api_weather_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherMessageResponse) ProtoMessage() {}

func (x *GetWeatherMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherMessageResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_weather_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_weather_weather_proto protoreflect.FileDescriptor

const file_api_weather_weather_proto_rawDesc = "" +
	"\n" +
	"\x19api/weather/weather.proto\x12\x0eapi.weather.v1\x1a\x1cgoogle/api/annotations.proto\".\n" +
	"\x18GetWeatherMessageRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"5\n" +
	"\x19GetWeatherMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x9f\x01\n" +
	"\x0eWeatherService\x12\x8c\x01\n" +
	"\x11GetWeatherMessage\x12(.api.weather.v1.GetWeatherMessageRequest\x1a).api.weather.v1.GetWeatherMessageResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/weather/{city}/messageB\x1fZ\x1dkratos-demo/api/weather/v1;v1b\x06proto3"

var (
	file_api_weather_weather_proto_rawDescOnce sync.Once
	file_api_weather_weather_proto_rawDescData []byte
)

func file_api_weather_weather_proto_rawDescGZIP() []byte {
	file_api_weather_weather_proto_rawDescOnce.Do(func() {
		file_api_weather_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_weather_weather_proto_rawDesc), len(file_api_weather_weather_proto_rawDesc)))
	})
	return file_api_weather_weather_proto_rawDescData
}

var file_api_weather_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_weather_weather_proto_goTypes = []any{
	(*GetWeatherMessageRequest)(nil),  // 0: api.weather.v1.GetWeatherMessageRequest
	(*GetWeatherMessageResponse)(nil), // 1: api.weather.v1.GetWeatherMessageResponse
}
var file_api_weather_weather_proto_depIdxs = []int32{
	0, // 0: api.weather.v1.WeatherService.GetWeatherMessage:input_type -> api.weather.v1.GetWeatherMessageRequest
	1, // 1: api.weather.v1.WeatherService.GetWeatherMessage:output_type -> api.weather.v1.GetWeatherMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_weather_weather_proto_init() }
func file_api_weather_weather_proto_init() {
	if File_api_weather_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_weather_weather_proto_rawDesc), len(file_api_weather_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_weather_weather_proto_goTypes,
		DependencyIndexes: file_api_weather_weather_proto_depIdxs,
		MessageInfos:      file_api_weather_weather_proto_msgTypes,
	}.Build()
	File_api_weather_weather_proto = out.File
	file_api_weather_weather_proto_goTypes = nil
	file_api_weather_weather_proto_depIdxs = nil
}
